pipeline {
    environment {
        GIT_BRANCH = "main"
        GITHUB_REPOSITORY_NAME = "JenkinsScripts"
        GITHUB_REPOSITORY = "github.com/hyu-x-ck24/${env.GITHUB_REPOSITORY_NAME}.git"
    }
    agent any
    
    stages {
        stage('Checkout') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'github_key', passwordVariable: 'GIT_PASSWORD', usernameVariable: 'GIT_USERNAME')]) {
                    git branch: env.GIT_BRANCH, url: "https://${GIT_USERNAME}:${GIT_PASSWORD}@${env.GITHUB_REPOSITORY}"ㅇ= ㅇ
                }
            }
        }
    }
}  